# Generated by Django 4.0 on 2022-01-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=400)),
                ('location', models.CharField(max_length=30)),
                ('from_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_date', models.DateField()),
                ('to_time', models.TimeField()),
                ('registration_end_date', models.DateField()),
                ('registration_end_time', models.TimeField()),
                ('host_email', models.EmailField(max_length=254)),
                ('host_password', models.TextField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
