# Generated by Django 4.0 on 2022-01-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host_password',
            field=models.CharField(max_length=30),
        ),
    ]
