# Generated by Django 4.0 on 2022-01-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='registration_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group')], default='Individual', max_length=30),
        ),
    ]
