# Generated by Django 4.0 on 2022-01-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_event_poster_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster_link',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
