# Generated by Django 4.0 on 2022-01-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_event_poster_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster_link',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(default='Choose Your Event', on_delete=django.db.models.deletion.CASCADE, to='registration.event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registration_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group')], default='Choose Participation Type', max_length=30),
        ),
    ]
