# Generated by Django 4.0 on 2022-01-06 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_event_poster_link_alter_participant_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='no_of_people',
            field=models.IntegerField(),
        ),
    ]
